---
title: "Prospectus"
author: "Nate Lant"
output: pdf_document
bibliography: bibliography.bib
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
biblio <- bibtex::read.bib("bibliography.bib")
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
 Cities across the world are concerned with understanding and forecasting the impacts of modern mobility systems. These systems — including dockless bike and scooter sharing, ridehailing via Transportation Network Companies (TNC), flexible route transit systems, and others — promise to greatly improve, or at least transform, urban mobility throughout the 21st century. As currently deployed however, such systems often presuppose a certain level of individual ability that not all transportation system users can achieve. Individuals who are physically disabled have reported difficulties using many of these systems [@Bascom2017]. For example, blind individuals may not be able to use a TNC’s mobile application, or a TNC driver’s vehicle is likely unsuitable for passengers who use wheelchairs. Seeing the opportunity afforded by modern mobility systems (especially TNCs) and the inability of some citizens to access them, some transportation agencies have begun to explore methods to improve system access for all users. These methods have included subsidized rides, driver training programs, and others. In one notable program, Lyft and the Utah Transit Authority (UTA) have proposed to offer wheelchair-dependent individuals the opportunity to hail a wheechair-accessible vehicle (WAV) through the Lyft application. Under the proposed agreement, Lyft drivers could serve the requests using a fleet of four WAVs provided under agreement with UTA. UTA would train the drivers to operate the special equipment and interface with wheelchair-dependent passengers. 

 A program such as that proposed by UTA with Lyft faces many legal and regulatory challenges, but it also faces non-trivial technical challenges related to understanding the relationship between supply and demand. What, for example, is the likely relationship between fleet size, fare, and level of service? A larger fleet will serve requests more quickly, but might be too expensive to operate. A smaller fleet might be too inconvenient for anyone to rely on for daily travel. Other questions surround the algorithm used to pair requests for trips with drivers; an optimal algorithm might achieve equivalent levels of service with a smaller fleet. These technical questions could be resolved, or at least rigorously studied, with a transportation supply and demand microsimulation. In this proposed research project, we will extend the robust, commonly-used transport microsimulation engine MATSim [@Axhausen2016] to model on-demand WAV mobility systems.


# Literature Review

## MATSim and Travel Demand Microsimulation
 MATSim is a Java-based multi-agent transportation microsimulation developed since 2006 by a team within the Institute for Land and Maritime Transportation at the Technical University of Berlin. MATSim combines a detailed link-level transportation simulation with an evolutionary algorithm to adjust individual daily plans and identify system optima. The agents in MATSim attempt to execute activity plans that require them to travel between their activities along transportation networks that become congested as people use them. At the end of a transportation simulation, each agent considers how much time they spent doing activities (generating a benefit) and how much time they spent traveling (losing benefits). Each agent will then adjust their plans — change departure time, use a different travel mode, take a different route, etc. — and after several dozen iterations, each simulated agent will have a complete daily plan that maximizes their personal benefit weighted against fares, incomes, vehicle constraints, the congestion created by the choices of others, etc. The combination of a detailed simulation with a simple but powerful plan updater has made MATSim appealing to many researchers seeking to understand complex modern mobility systems. Extensions to MATSim have enabled to researchers to examine carsharing in Zürich [@Balac] autonomous vehicle replacement scenarios in Berlin [@BischoffJ2016] and Asheville, North Carolina [@Kressner], demand-reponsive and autonomous transit in Braunschweig [@Cyganski2018], incident and disaster response in the Philippines [@Yaneza2016], and first-mile / last-mile connectivity in the San Francisco Bay, California [@Jaller2019]. 

## Mobility For the Disabled
In 2018, the Taxi and Limousine Commission (TLC) in New York City issued a mandate requiring Uber, Lyft and Via to make wheelchair accessible service a growing part of their operations. While this particular mandate was not adopted, a settlement was reached in the New York State Supreme Court. The NYC TLC retained the mandate that would require TNCs to meet a wait-time requirement. The wait time requirement states that, by 2021, TNCs must either service at least 80 percent of requests for wheelchair-accessible vehicles in under 10 minutes and 90 percent in under 15 minutes, or associate with a company that has the capacity to meet those requirements [@Report2019].

In September of 2018, the State of California filed SB 1376 which "requires the Public Utilities Commission, by January 1, 2019, to begin conducting workshops with stakeholders in order to determine community WAV demand and WAV supply and to develop and provide recommendations regarding specified topics for programs for on-demand services and partnerships. The bill would require each TNC, by July 1, 2019, to pay on a quarterly basis to the commission an amount equivalent to, at a minimum, $0.05 for each TNC trip completed. The bill would require moneys collected by the commission to be deposited in the TNC Access for All Fund, which the bill would create, and would continuously appropriate moneys deposited in the fund to the commission for purposes of the program. The bill would require the commission to distribute funds from the TNC Access for All Fund on a competitive basis to access providers that establish on-demand transportation programs or partnerships to meet the needs of persons with disabilities." [@California2019].

The U.S. Department of Transportation published that people with travel-limiting disabilities accounted for 8.5 percent of the population in 2001 and 10.2 percent in 2009. An estimated 13.4 million Americans age 18 to 64 have travel-limiting disabilities, accounting for slightly more than half of people with disabilities [@Brumbaugh2018]. This report states that 12.4 percent of people age 18 to 64 without disabilities report using ride-hailing services at least once in the last 30 days, only 4.6 percent of people with disabilities report doing so. Some organizations, including transit agencies and healthcare providers, have begun subsidizing ride-hailing services for people with disabilities.


# Research Proposal and Objectives
The main objective of this research is to simulate on-demand mobility for users with wheelchairs in Salt Lake City. A key component of the research will be extending MATSim to represent the two population problem. This research will lead to the development of a mechanism to understand the operation of WAV deployments and the relationship among demand for such system and variables like fare, fleet size, weather, wait time, etc. The research may also lead to further understanding of travel behavior for users with wheelchairs.

## Building the Daily Activity Pattern
Daily activity patterns for abled and disabled individuals for the MATSim simulation scenarios will come from an activity-based model representing the geographic region of Salt Lake City. The open-source ActivitySim project will supply these daily activity patterns, which currently account only for the mobility of abled individuals. This research will need to extend the model to account for wheelchair mobility, either by configuring ActivitySim to produce daily patterns of disabled individuals or by identifying existing daily activity patterns that are plausible for disabled individuals. These two groups of daily activity plans (for abled and disabled individuals) will be input into the MATSim scenarios.

## Extending MATSim to WAV

 The existing mobility-as-a-service (MAAS) and demand-responsive transit (DRT) modules within MATSim assume a single homogeneous population of passengers and drivers. That is, any ride request can be handled by any vehicle, and any driver agent can handle any request. In the on-demand WAV system proposed by UTA, this will not be the case. Ride requests coming from conventional passengers might be handled by conventional vehicles or by WAVs, though WAVs might prioritize requests from wheelchair users. Conversely, wheelchair users will be unable to use conventional vehicles. In order to adequately represent this system, it will be necessary to extend the existing MATSim MAAS and DRT modules to enable the heuristics to discriminate between ride requests from these two populations.
 
 It should be noted that this extension could be an important component of simulations of other emerging transportation solutions platforms. For example, privately owned autonomous vehicles may be used as for-hire taxis when unneeded by their primary owner; it is conceivable that such vehicles may only serve ride requests from members of certain clubs or networks. Even representing competition between two large-scale TNCs within a single metropolitan area may require request discrimination or prioritization that would be represented within a microsimulation by a fractured demand and supply. 

## Project Description and Schedule
 As described above, the overall goal of this project is to develop a simulation model that will help UTA understand possible responses to proposed on-demand transit and mobility offerings. The model will estimate measures of performance such as WAV utilization, wait time, and the share of riders who opt for WAV over conventional transit operations. The resulting tool will provide a mechanism to understand the tradeoffs and synergies between conventional transit and ondemand mobility services, and how such services could optimize their supply and request handling algorithms.
 
### Scenarios
The scenarios will be informed by the capabilities we are able to introduce to MATSim, and are likely to include adjustments to the following elements:

 + The algorithm used to pair drivers with ride requests, specifically regarding the way in which WAV drivers will prioritize wheelchair passengers 
 
 + The size of the wheelchair-bound population 
 
 + The size and spatial dispersion of the WAV fleet 
 
The scenarios will be evaluated on the share of WAV trips by wheelchair-bound and general users, the simulated delay for WAV requests, and the mode share of the wheelchair-bound population. 

### Schedule

 + **December 2019 - March 2020** -  Generate daily activity patterns for both the general and the wheechair-bound populations. The general population  plans will be supplied by an ActivitySim (ActivitySim Consortium, 2019) implementation in Salt Lake City. The wheelchair-bound population will be adapted from the general population and modified to reflect differences in travel patterns observed in the literature. 
 
 + **March - May 2020** - Implement the Salt Lake City scenario in MATSim with MAAS extensions. 
 
 + **May - June 2020** -  Extend the MATSim MAAS and DRT modules to support heterogenous fleets and populations.
 
 + **June - July 2020** - Test and debug the simulation model in MATSim, and design alternative algorithms and scenarios that could be analyzed. 
 
 + **August - October 2020** -  Apply simulation model and analyze the full-population WAV scenarios.
 
 + **November 2020** - Present results of simulation scenarios to UTA, defend MS Thesis. 
 


# Conclusion
 As a culminating project for my undergraduate degree, I led a team of students in working with UTA to design and evaluate the prospective WAV system discussed previously. My team organized existing UTA data on wheelchair ramp deployments and existing paratransit customers; these data informed a geospatial analysis of where the on-demand WAV system would be most successful. We also evaluated the potential costs of such a system, considering fuel consumption, driver wage subsidies, and vehicle maintenance. Finally, we wrote the Request for Proposals which two major TNCs responded to, and developed an evaluation plan that UTA and the respondent TNC would use to determine the success of their cooperative efforts. Leading this project helped me see major challenges related to public private parternships. It also showed me the gaps in the current understanding of mobility service demand within an actual transit agency.  A microsimulation such as outlined in this proposal would provide a tool to organize and test many of the assumptions made in the pilot between UTA and Lyft—e.g. fare, origin-destination patterns—and evaluate each assumption’s influence on the overall project outcomes. Many lives, including my own, have been improved by modern mobility systems that can make travel through cities convenient, flexible, and relatively affordable. I am eager to look at ways to make these benefits extend to those who have been to this point left behind. The results of this study have a potential to directly improve the lives of wheelchair dependent individuals in Salt Lake City in the relatively short term, and many other cities going forward.
 
# References


